# Generated by Django 3.0.3 on 2020-07-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200630_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_nurse',
            field=models.BooleanField(default=True),
        ),
    ]
