# Generated by Django 3.0 on 2020-02-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200223_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateField(auto_now_add=True, default='2020-02-23'),
            preserve_default=False,
        ),
    ]
