# Generated by Django 3.0.3 on 2020-07-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200703_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_nurse',
            field=models.BooleanField(default=False),
        ),
    ]
