# Generated by Django 3.0.3 on 2020-07-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200703_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ec_email_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
