# Generated by Django 3.0.3 on 2020-07-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200707_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/media/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
