# Generated by Django 3.0 on 2020-06-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200420_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ec_phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
