# Generated by Django 3.0.3 on 2020-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200703_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ec_phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
