# Generated by Django 3.0.3 on 2020-07-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_avatar'),
        ('users', '0003_auto_20200710_1611'),
    ]

    operations = [
    ]
