# Generated by Django 3.0 on 2020-06-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientZone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='nurse_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='nurse_name',
            new_name='staff_name',
        ),
        migrations.AddField(
            model_name='comments',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='patient_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
