# Generated by Django 3.0.3 on 2020-06-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientZone', '0002_auto_20200614_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
