# Generated by Django 3.0 on 2020-07-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientZone', '0004_auto_20200621_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted']},
        ),
    ]
