# Generated by Django 3.0 on 2020-07-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientZone', '0005_auto_20200710_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
