# Generated by Django 3.0.3 on 2020-07-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientZone', '0006_auto_20200710_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='show_patient',
            field=models.BooleanField(default=False),
        ),
    ]
