# Generated by Django 3.0.3 on 2020-07-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientZone', '0008_comment_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='patient',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
    ]
