# Generated by Django 3.0.3 on 2020-07-31 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patientZone', '0011_auto_20200729_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
